global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "T2_US_TEST"
    static_configs:
    - targets: ["pi.aashayarora.com:9100"]
